### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by mnording** [AceMetrix/youtrack-rest-node-library#1]
Im currently unable to connect to a youtrack insstance inside of a self signed certificate
even with the process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

the youtrack.login('username, password', function(err){ returns no error

**Comment by anacronw** [comment]
Hm, i didn't think about that use case. I can see how that could cause issues, however.  Request seems to have a problem with it: https://github.com/mikeal/request/issues/418.

I'll look into supporting some configuration that'll relax the strictSSL

**Comment by anacronw** [comment]
Please try the following after updating the package

```
var youtrack = new Connection('http://your-youtrack-instance:8080', {strictSSL: false});
youtrack.login('username', 'password', function(err){
})
```

I basically pass any options you give the connection over to request.

As you may have already guessed, the library doesn't do anything except logging in at this point...still I do wish to flesh it out soon.
